!include <win32.mak>

all: srv_leafinfo.Dll

.c.obj:
	$(cc) /I..\..\include /I..\..\ $(cdebug) $(cflags) $(cvarsdll) -I. -DCI_BUILD_MODULE -DUNICODE $*.c

srv_leafinfo.Dll: leafinfo.obj
	$(link) $(linkdebug) $(dlllflags) /LIBPATH:..\..\ c_icap.lib -def:srv_leafinfo.def -out:$*.Dll $** $(DLL_ENTRY)  $(EXTRA_LIBS)

clean:
	del *.obj *.exe *.lib

